# Generated by Django 4.2.13 on 2024-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blab',
            fields=[
                ('blabid', models.IntegerField(primary_key=True, serialize=False, verbose_name='max_length=11')),
                ('blabber', models.TextField(max_length=100)),
                ('timestamp', models.DateTimeField(null=True)),
                ('content', models.TextField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'blabs',
            },
        ),
        migrations.CreateModel(
            name='Blabber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('realName', models.TextField(max_length=100)),
                ('blabName', models.TextField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('numberListeners', models.IntegerField(default=0)),
                ('numberListening', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.IntegerField(primary_key=True, serialize=False)),
                ('blabid', models.IntegerField()),
                ('blabber', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=250, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blabber', models.TextField(max_length=100)),
                ('listener', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'listeners',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('password_hint', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('real_name', models.CharField(max_length=100, null=True)),
                ('blab_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_History',
            fields=[
                ('eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('blabber', models.TextField(max_length=100)),
                ('event', models.TextField(max_length=250, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users_history',
            },
        ),
    ]
